config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'auth', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }

devise_scope :user do
  match 'active'  => 'users/sessions#active',  via: :get
  match 'timeout' => 'users/sessions#timeout', via: :get
end

  root to: 'home#index'

  resources :incidents

  resources :facilities

  resources :injuries

  resources :thefts

  resources :vehicle_accidents

  resources :behaviourals

  resources :property_damages

  resources :misconducts

  resources :users

  resources :incident_types

  resources :severity_levels

  resources :reports do
    collection do
      match 'search' => 'reports#search', via: [:get, :post], as: :search
    end
  end

  resources :areas

  resources :programs

  resources :buses

end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :facility_areas, dependent: :destroy
	has_many :facilities, through: :facility_areas
end

app/models/behavioural.rb
class Behavioural < ActiveRecord::Base
	belongs_to :incident
end

app/models/bus.rb
class Bus < ActiveRecord::Base
	serialize :assigned_facilities
	serialize :assigned_programs
end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :facility_areas, :dependent => :destroy
	has_many :areas, :through => :facility_areas
	has_many :facility_programs, :dependent => :destroy
	has_many :programs, :through => :facility_programs
	accepts_nested_attributes_for :facility_areas, :allow_destroy => true
	accepts_nested_attributes_for :facility_programs, :allow_destroy => true
end

app/models/facility_area.rb
class FacilityArea < ActiveRecord::Base
	belongs_to :facility
	belongs_to :area

	validates_uniqueness_of :area_id, :scope => :facility_id
end

app/models/facility_program.rb
class FacilityProgram < ActiveRecord::Base
	belongs_to :facility
	belongs_to :program

	validates_uniqueness_of :program_id, :scope => :facility_id
end

app/models/incident.rb
class Incident < ActiveRecord::Base
	belongs_to :facility
	has_many :injuries, dependent: :destroy
	has_many :misconducts, dependent: :destroy
	has_many :behaviourals, dependent: :destroy
	has_many :thefts, dependent: :destroy
	has_many :vehicle_accidents, dependent: :destroy
	has_many :property_damages, dependent: :destroy
	accepts_nested_attributes_for :injuries, :allow_destroy => true, :reject_if => proc { |attr| attr[:injury_description].blank? }
	accepts_nested_attributes_for :misconducts, :allow_destroy => true, :reject_if => proc { |attr| attr[:misconduct_description].blank? }
	accepts_nested_attributes_for :behaviourals, :allow_destroy => true, :reject_if => proc { |attr| attr[:behav_description].blank? }
	accepts_nested_attributes_for :thefts, :allow_destroy => true, :reject_if => proc { |attr| attr[:theft_description].blank? }
	accepts_nested_attributes_for :vehicle_accidents, :allow_destroy => true, :reject_if => proc { |attr| attr[:veh_description].blank? }
	accepts_nested_attributes_for :property_damages, :allow_destroy => true, :reject_if => proc { |attr| attr[:prop_description].blank? }


	ransacker :id do
	  Arel::Nodes::SqlLiteral.new("substring(CAST(#{table_name}.id as CHAR(12)),length(id))")
	end

	ransacker :area_id do
	  Arel::Nodes::SqlLiteral.new("substring(CAST(#{table_name}.area_id as CHAR(12)),length(area_id))")
	end

	ransacker :program_id do
	  Arel::Nodes::SqlLiteral.new("substring(CAST(#{table_name}.program_id as CHAR(12)),length(program_id))")
	end
end

app/models/incident_type.rb
class IncidentType < ActiveRecord::Base
	belongs_to :incident_detail
end

app/models/injury.rb
class Injury < ActiveRecord::Base
	belongs_to :incident

	def injury_string
		"Injury - #{id}"
	end
end

app/models/involved_type.rb
class InvolvedType < ActiveRecord::Base
	belongs_to :incident_detail
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :incident
end

app/models/misconduct.rb
class Misconduct < ActiveRecord::Base
	belongs_to :incident
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :facility_programs, dependent: :destroy
	has_many :facilities, through: :facility_programs
end

app/models/property_damage.rb
class PropertyDamage < ActiveRecord::Base
	belongs_to :incident
end

app/models/severity_level.rb
class SeverityLevel < ActiveRecord::Base
	belongs_to :incident_detail
end

app/models/theft.rb
class Theft < ActiveRecord::Base
	belongs_to :incident
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  validates_presence_of :username

  serialize :facility_id
  serialize :program_id

  def password_required?
    new_record? ? false : super
  end

  def email_required?
    true
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  before_filter :authenticate_user!, :check_if_admin
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  def check_if_admin
    return unless !current_user.admin?
    redirect_to root_path, alert: 'Admins only!'
  end

  def index
    add_breadcrumb "Program", :programs_path
  	@programs = Program.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @program = Program.new
  end

  def create
    @program = Program.create(program_params)

    respond_to do |format|
      if @program.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @program.errors.full_messages,
                            status: :unprocessable_entry }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @program.update(program_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @program.errors.full_messages,
                                   status: :unprocessable_entry }
      end
    end
  end

  def destroy
    @program.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to programs_url}
      format.json { head :no_content}
    end
  end

private

  def set_program
    @program = Program.find(params[:id])
  end

  def program_params
    params.require(:program).permit(:name)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incident_helper.rb
module IncidentHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/programs/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/programs/_form.html.erb
<%= nested_form_for(@program, remote: true, :html => { :role => "form" }) do |f| %>
  <div id="error_explanation" class="bg-danger text-danger">

  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :name, :class => "control-label" %>
        <%= f.text_field :name, :class => "form-control" %>
      </div>  
    </div>
  </div>

  <div class="row">
    <div class="text-center">
      <div class="form-group">
        <%= f.submit  @program.new_record? ? "Create Program" : "Update Program", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/programs/_program.html.erb
<tr id="program_<%= program.id %>">
    <td><%= program.name %></td>
    <td>
	    <%= link_to 'Edit', edit_program_path(program), remote: true, :class => 'btn btn-sm btn-primary' %>
	</td>
    <td>
	    <%= link_to 'Delete', program, remote: true, :method => :delete, data: {confirm: "Delete Program: #{program.id}"}, :class => 'btn btn-sm btn-primary' %>
	</td>
</tr>

app/views/programs/create.js.erb
$('#dialog').modal('toggle');
$('#programs').append('<%= j render (@program) %>')

app/views/programs/destroy.js.erb
$('#program_<%= @program.id %>').fadeOut();

app/views/programs/edit.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Program");
 
// Render the edit form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/programs/index.html.erb
<div class='col-md-10 col-md-offset-1'>
  <h2>Programs</h2>
  <%= link_to "New Program", new_program_path, remote: true, class: "btn btn-primary" %>
  <hr>
  <div class='panel panel-default'>
    <div class='panel-body'>
      <div class="table-responsive">
        <table class="table table-hover table-striped table-bordered">
          <thead>
            <tr>
              <th>Program Name</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody id="programs">
          <div class = "sort_paginate_ajax"><%= render @programs %></div>
          </tbody>
        </table>
        <%= will_paginate @programs, renderer: BootstrapPagination::Rails %>
      </div>

      <%= render 'dialog' %>

    </div>
  </div>
</div>

app/views/programs/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render("programs"))%>")

app/views/programs/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Add New Program");
 
// Render the new form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus()
  })

app/views/programs/update.js.erb
$('#dialog').modal('toggle');
$('#program_<%= @program.id %>').replaceWith('<%= j render (@program) %>')