config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'auth', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    invitations: 'users/invitations'
  }

devise_scope :user do
  match 'active'  => 'users/sessions#active',  via: :get
  match 'timeout' => 'users/sessions#timeout', via: :get
end

  root to: 'home#index'

  resources :incidents

  resources :facilities

  resources :injuries

  resources :thefts

  resources :vehicle_accidents

  resources :behaviourals

  resources :property_damages

  resources :misconducts

  resources :users

  resources :incident_types

  resources :severity_levels

  resources :reports do
    collection do
      match 'search' => 'reports#search', via: [:get, :post], as: :search
    end
  end

  resources :areas

  resources :programs

  resources :buses

end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :facility_areas, dependent: :destroy
	has_many :facilities, through: :facility_areas
end

app/models/behavioural.rb
class Behavioural < ActiveRecord::Base
	belongs_to :incident
end

app/models/bus.rb
class Bus < ActiveRecord::Base
	serialize :assigned_facilities
	serialize :assigned_programs
end

app/models/facility.rb
class Facility < ActiveRecord::Base
	has_many :facility_areas, :dependent => :destroy
	has_many :areas, :through => :facility_areas
	has_many :facility_programs, :dependent => :destroy
	has_many :programs, :through => :facility_programs
	accepts_nested_attributes_for :facility_areas, :allow_destroy => true
	accepts_nested_attributes_for :facility_programs, :allow_destroy => true
end

app/models/facility_area.rb
class FacilityArea < ActiveRecord::Base
	belongs_to :facility
	belongs_to :area

	validates_uniqueness_of :area_id, :scope => :facility_id
end

app/models/incident.rb
class Incident < ActiveRecord::Base
	belongs_to :facility
	has_many :injuries, dependent: :destroy
	has_many :misconducts, dependent: :destroy
	has_many :behaviourals, dependent: :destroy
	has_many :thefts, dependent: :destroy
	has_many :vehicle_accidents, dependent: :destroy
	has_many :property_damages, dependent: :destroy
	accepts_nested_attributes_for :injuries, :allow_destroy => true, :reject_if => proc { |attr| attr[:injury_description].blank? }
	accepts_nested_attributes_for :misconducts, :allow_destroy => true, :reject_if => proc { |attr| attr[:misconduct_description].blank? }
	accepts_nested_attributes_for :behaviourals, :allow_destroy => true, :reject_if => proc { |attr| attr[:behav_description].blank? }
	accepts_nested_attributes_for :thefts, :allow_destroy => true, :reject_if => proc { |attr| attr[:theft_description].blank? }
	accepts_nested_attributes_for :vehicle_accidents, :allow_destroy => true, :reject_if => proc { |attr| attr[:veh_description].blank? }
	accepts_nested_attributes_for :property_damages, :allow_destroy => true, :reject_if => proc { |attr| attr[:prop_description].blank? }


	ransacker :id do
	  Arel::Nodes::SqlLiteral.new("substring(CAST(#{table_name}.id as CHAR(12)),length(id))")
	end

	ransacker :area_id do
	  Arel::Nodes::SqlLiteral.new("substring(CAST(#{table_name}.area_id as CHAR(12)),length(area_id))")
	end

	ransacker :program_id do
	  Arel::Nodes::SqlLiteral.new("substring(CAST(#{table_name}.program_id as CHAR(12)),length(program_id))")
	end
end

app/models/incident_type.rb
class IncidentType < ActiveRecord::Base
	belongs_to :incident_detail
end

app/models/injury.rb
class Injury < ActiveRecord::Base
	belongs_to :incident

	def injury_string
		"Injury - #{id}"
	end
end

app/models/involved_type.rb
class InvolvedType < ActiveRecord::Base
	belongs_to :incident_detail
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :incident
end

app/models/misconduct.rb
class Misconduct < ActiveRecord::Base
	belongs_to :incident
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :facility_programs, dependent: :destroy
	has_many :facilities, through: :facility_programs
end

app/models/property_damage.rb
class PropertyDamage < ActiveRecord::Base
	belongs_to :incident
end

app/models/severity_level.rb
class SeverityLevel < ActiveRecord::Base
	belongs_to :incident_detail
end

app/models/theft.rb
class Theft < ActiveRecord::Base
	belongs_to :incident
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :invitable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  validates_presence_of :username

  serialize :facility_id
  serialize :program_id

  def password_required?
    new_record? ? false : super
  end

  def email_required?
    true
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incident_helper.rb
module IncidentHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/partials/_general.html.erb
<div class="row">
	<div class="col-sm-6">
		<div class="form-group">
			<%= f.label :date_reported, "Date and Time Reported", :class => "control-label" %>
			<div class='input-group date' id='date_reported'>
				<%= f.text_field :date_reported, :value => @sysDateTime, :class => "form-control", "data-provide" => 'datepicker', :readonly => true %>
				<span class="input-group-addon">
				<span class="glyphicon glyphicon-calendar"></span>
				</span>
			</div>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="form-group">
			<%= f.label :date_of_incident, "Date and Time of Incident", :class => "control-label" %>
			<div class='input-group date' id='date_of_incident'>
				<%= f.text_field :date_of_incident, :class => "form-control", "data-provide" => 'datepicker' %>
				<span class="input-group-addon">
				<span class="glyphicon glyphicon-calendar"></span>
				</span>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-6">
		<div class="form-group">
		<%= f.label :reporter, :class => "control-label" %>
		<%= f.text_field :reporter, :value => current_user.first_name+" "+current_user.last_name , :class => "form-control", :readonly => true  %>
		</div>  
	</div>

	<div class="col-sm-6">
		<div class="form-group">
			<%= f.label :witness, :class => "control-label" %>
			<%= f.text_field :witness, :class => "form-control" %>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-6">
		<div class="form-group">
			<%= f.label :location_id, :class => "control-label" %>
			<%= f.select :location_id, Location.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, {:class => 'form-control'} %>
		</div>
	</div>
	<div id="loc-fac">
		<div class="col-sm-6">
			<div class="form-group">
				<%= f.label :facility_id, :class => "control-label" %>
				<%= f.collection_select :facility_id, Facility.all, :id, :name, {:prompt => 'Please select a facility...'}, {:class => 'form-control'} %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div id="loc-area">
		<div class="col-sm-6">
			<div class="form-group">
				<%= f.label :area_id, :class => "control-label" %>
				<%= f.grouped_collection_select :area_id, Facility.all, :areas,  :name, :id, :name, {}, {:class => 'form-control'} %>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="form-group">
				<%= f.label :program_id, :class => "control-label" %>
				<%= f.grouped_collection_select :program_id, Facility.all, :programs, :name, :id, :name, {}, {:class => 'form-control'} %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div id="loc-address">
		<div class="col-md-12">
			<div class="form-group">
				<%= f.label :physical_address, :class => "control-label" %>
				<%= f.text_field :physical_address, :class => "form-control" %>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<div class="form-group">
			<%= f.label :severity_level_id, :class => "control-label" %>
			<%= f.collection_select :severity_level_id, SeverityLevel.all, :id, :name, {:prompt => 'Severity...'}, {:class => 'form-control'} %>
		</div>
	</div>
	<div class="col-md-6">
		<div class="form-group">
			<ul class="list-group">
				<li class="list-group-item disabled">
					Incident Emergency/Insurance
				</li>
		        <li class="list-group-item">
		            Emergency contacted?
		            <div class="material-switch pull-right" style="padding-top: 10px;">
	        			<%= f.check_box :emergency_notified %>
		                <label for="<%= form_tag_id(f.object_name, :emergency_notified) %>" class="label-primary"></label>
		            </div>
		        </li>
		        <li class="list-group-item">
		            Insurance claim filed?
		            <div class="material-switch pull-right" style="padding-top: 10px;">
		                <%= f.check_box :insurance_filed %>
		                <label for="<%= form_tag_id(f.object_name, :insurance_filed) %>" class="label-primary"></label>
		            </div>
		        </li>
		    </ul>
	    </div>
    </div>
</div>
<div id="<%= form_tag_id(f.object_name, :emergency_info) %>">
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<%= f.label :emergency_detail, "Police Report Info:", :class => "control-label" %>
				<%= f.text_area :emergency_detail, :class => "form-control", :rows => "3" %>
			</div>
		</div>
	</div>
</div>

<div id="<%= form_tag_id(f.object_name, :insurance_info) %>">
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<%= f.label :insurance_detail, "Insurance Claim Info:", :class => "control-label" %>
				<%= f.text_area :insurance_detail, :class => "form-control", :rows => "3" %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="form-group">
			<%= f.label :description, "General Overview of Incident", :class => "control-label" %>
			<%= f.text_area :description, :class => "form-control", :rows => "3" %>
		</div>
	</div>
</div>

<script>
	areas = $('#incident_area_id').html();
	programs = $('#incident_program_id').html();
	$('#incident_facility_id').on('change', function() {
		facility = $('#incident_facility_id :selected').text();
		area_options = $(areas).filter('optgroup[label="#facility"]'.replace('#facility', facility)).html();
		program_options = $(programs).filter('optgroup[label="#facility"]'.replace('#facility', facility)).html();
		if (area_options) {
			$('#incident_area_id').html(area_options);
		}
		else {
			$('#incident_area_id').empty();
		}
		if (program_options) {
			$('#incident_program_id').html(program_options);
		}
		else {
			$('#incident_program_id').empty();
		}
	}).trigger('change');


	$('#<%= form_tag_id(f.object_name, :emergency_notified) %>').change(function() {
		if ( $(this).is(':checked') )
		{
        	$("div#<%= form_tag_id(f.object_name, :emergency_info) %>").show();
        }
        else
		{
        	$("div#<%= form_tag_id(f.object_name, :emergency_info) %>").hide();
        }
    }).trigger('change');

	$('#<%= form_tag_id(f.object_name, :insurance_filed) %>').change(function() {
		if ( $(this).is(':checked') )
		{
        	$("div#<%= form_tag_id(f.object_name, :insurance_info) %>").show();
        }
        else
		{
        	$("div#<%= form_tag_id(f.object_name, :insurance_info) %>").hide();
        }
    }).trigger('change');    
</script>

app/views/partials/_injury.html.erb
<%= f.fields_for :injuries do |injury_builder| %>
<div class="row">
	<div class="col-sm-6">
	      <div class="form-group">
			<%= injury_builder.label :injury_involved_type_id, "Invovled Type:", :class => "control-label" %>
	        <%= injury_builder.select :injury_involved_type_id, InvolvedType.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, {:class => 'form-control'} %>
		</div>
	</div>
	<div class="col-sm-6">
	      <div class="form-group">
			<%= injury_builder.label :injury_involved_name, "Involved Name:", :class => "control-label" %>
	        <%= injury_builder.text_field :injury_involved_name, :class => "form-control" %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="form-group">
			<%= injury_builder.label :injury_description, "Injury Description:", :class => "control-label" %>
			<%= injury_builder.text_area :injury_description, :class => "form-control", :rows => "3" %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
	      <div class="form-group">
			<%= injury_builder.label :injury_first_aid, "What medical care was provided?", :class => "control-label" %>
	        <%= injury_builder.text_area :injury_first_aid, :class => "form-control", :rows => "3" %>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-1">
	</div>
	<div class="col-sm-1">
			<%= injury_builder.label :injury_guardian_notified, "Parent notified", :class => "control-label" %>
	        <%= injury_builder.check_box :injury_guardian_notified, :class => "form-control" %>
	</div>
</div>
<div id="incident_injuries_guardian_info">
	<div class="row">
		<div class="col-sm-6">
			<div class="form-group">
				<%= injury_builder.label :injury_guardian_name, "Parent Name", :class => "control-label" %>
		        <%= injury_builder.text_field :injury_guardian_name, :class => "form-control" %>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="form-group">
				<%= injury_builder.label :injury_guardian_number, "Parent Number", :class => "control-label" %>
		        <%= injury_builder.text_field :injury_guardian_number, :class => "form-control" %>
			</div>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
	      <div class="form-group">
			<%= injury_builder.label :injury_followup, "Follow-up Notes:", :class => "control-label" %>
	        <%= injury_builder.text_area :injury_followup, :class => "form-control", :rows => "3" %>
		</div>
	</div>
</div>
<% end %>

<script type="text/javascript">
	$(document).ready(function(){
	    $('#incident_injuries_attributes_0_injury_guardian_notified').change(function() {
			if ( $(this).is(':checked') )
			{
	        	$("div#incident_injuries_guardian_info").show();
	        }
	        else
			{
	        	$("div#incident_injuries_guardian_info").hide();
	        }
	    }).trigger('change');
	});
</script>

app/views/partials/_misconduct.html.erb
<%= f.fields_for :misconducts do |ff| %>
	<div class="panel panel-default">
		<div class="panel-heading">Misconduct</div>
		<div class="panel-body" style="padding-bottom: 0px">	
			<div class="row">
				<div class="col-sm-12">
					<div class="form-group">
						<%= ff.label :misconduct_description, "What occured?", :class => "control-label" %>
						<%= ff.text_area :misconduct_description, :class => "form-control", :rows => "3" %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<ul class="list-group">
							<li class="list-group-item">
							Parent notified?
							    <div class="material-switch pull-right" style="padding-top: 10px;">
				        	        <%= ff.check_box :misconduct_cps_notified %>
				            	    <label for="<%= form_tag_id(ff.object_name, :misconduct_cps_notified) %>" class="label-primary"></label>
					            </div>
					        </li>
				        </ul>
	        	    </div>
           		</div>
			</div>

			<div id="misconduct_incident_detail_cps_info">
				<div class="row">
					<div class="col-sm-12">
						<div class="form-group">
							<%= ff.label :misconduct_cps_detail, "CPS Info:", :class => "control-label" %>
					        <%= ff.text_area :misconduct_cps_detail, :class => "form-control", :rows => "3" %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="panel-footer clearfix">
			<div class="pull-right">
			</div>
		</div>
	</div>
<% end %>


<script type="text/javascript">
	$(document).ready(function(){
		$('#incident_misconducts_attributes_0_misconduct_cps_notified').change(function() {
			if ( $(this).is(':checked') )
			{
	        	$("div#misconduct_incident_detail_cps_info").show();
	        }
	        else
			{
	        	$("div#misconduct_incident_detail_cps_info").hide();
	        }
	    }).trigger('change');
	});
</script>

app/views/shared/_forgot.html.erb
<div class="modal fade" id="login">
  <div class="vertical-alignment-helper">
    <div class="modal-dialog vertical-align-center">
      <div class="loginmodal-container">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h1>Login to Your Account</h1><br>
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
          <div>
            <%= f.text_field :username, :autofocus => true, :placeholder => "Username" %>
          </div>
          <div>
            <%= f.password_field :password, :placeholder => "Password" %>
          </div>
          <% if devise_mapping.rememberable? -%>
          <div>
            <%= f.check_box :remember_me %> <%= f.label :remember_me %>
          </div>
          <% end -%>
          <%= f.submit "Login", :class => 'login loginmodal-submit' %>
        <% end %>
        <div class="login-help">
          <!-- <a href="#">Forgot Password</a> -->
          <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_login.html.erb
<div class="modal fade" id="login">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h2>Sign in</h2>
      </div>
      <div class="modal-body">
        <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
          <div>
            <%= f.label :username %><br />
            <%= f.text_field :username, :autofocus => true %>
          </div>
          <div>
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>
          <% if devise_mapping.rememberable? -%>
          <div>
            <%= f.check_box :remember_me %> <%= f.label :remember_me %>
          </div>
          <% end -%>
          <%= f.submit "Sign in", :class => 'btn btn-small btn-success' %>
        <% end %>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/shared/_mobile_nav.html.erb
<ul class="nav navbar-nav hidden-lg">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-left: 20px">General <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to "Home", root_path, {:style => 'margin-left: 20px'} %>
      </li>
      <li>
        <%= link_to "Incidents", incidents_path, {:style => 'margin-left: 20px'} %>
      </li>
      <li>
        <%= link_to "Reporting", reports_path, {:style => 'margin-left: 20px'} %>
      </li>
    </ul>
  </li>
</ul>
<% if current_user.try(:admin?) %>
  <ul class="nav navbar-nav hidden-lg">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="margin-left: 20px">Admin <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "Users", users_path, {:style => 'margin-left: 20px'} %>
        </li>
        <li>
          <%= link_to "Facilities", facilities_path, {:style => 'margin-left: 20px'} %>
        </li>
        <li>
          <%= link_to "Areas", areas_path, {:style => 'margin-left: 20px'} %>
        </li>
        <li>
          <%= link_to "Programs", programs_path, {:style => 'margin-left: 20px'} %>
        </li>
        <li>
          <%= link_to "Bus List", buses_path, {:style => 'margin-left: 20px'} %>
        </li>
<!--         <li>
          <%= link_to "Incident Types", incident_types_path, {:style => 'margin-left: 20px'} %>
        </li> -->
        <li>
          <%= link_to "Severity Levels", severity_levels_path, {:style => 'margin-left: 20px'} %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<% if notice %>
  <div id="notice_wrapper">
    <p class="notice"><%= notice %></p>
  </div>
<% elsif alert %>
  <div id="alert_wrapper">
    <p class="alert"><%= alert %></p>
  </div>
<% end %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" style="margin-top: -13px">
        <span><img style="max-width:50px;background-color: rgba(255, 255, 255, 0)" src="/assets/images/logo.png"></span>
        Incident Reporting
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= render 'shared/sidebar' %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= render 'shared/mobile_nav' %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user" aria-hidden="true"></span><i class="fa fa-user"></i> <%= current_user.username %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <i class="fa fa-fw fa-user"></i><%= link_to "Profile", edit_user_registration_path %>
              </li>
              <li>
                <i class="fa fa-fw fa-power-off"></i><%= link_to "Logout", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-off" aria-hidden="true"></span><i class="fa fa-user"></i> Login <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>  
                <i class="fa fa-fw fa-power-off"></i><%= link_to 'Login', '#login', {'data-toggle' => "modal", 'data-target' => '#login'} %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
      <%= search_form_for @q, url: search_reports_path, :class => "navbar-form navbar-right", html: { method: :post }  do |f| %>
          <%= f.text_field :id_or_reporter_or_witness_cont, :class => "form-control", :placeholder => "Search..." %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_pageheading.html.erb
<ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => "" %>
</ol>

app/views/shared/_sidebar.html.erb
<div class="col-md-0 col-lg-2 sidebar hidden-md hidden-sm">
  <ul class="nav nav-sidebar">
  	<li class="nav-divider"></li>
    <li class="dropdown-header">General</li>
    <li>
    	<%= active_link_to "Home", root_path, :wrap_tag => :li, :active => :exclusive %>
    </li>
    <li>
    	<%= active_link_to "Incidents", incidents_path, :wrap_tag => :li if current_user %>
    </li>
    <li>
        <%= active_link_to "Reporting", reports_path, :wrap_tag => :li if current_user %>
    </li>
    <% if current_user.try(:admin?) %>
        <li class="nav-divider"></li>
        <li class="dropdown-header">Admin</li>
        <li>
        	<%= active_link_to "Users", users_path, :wrap_tag => :li if current_user.try(:admin?) %>
        </li>
        <li>
            <%= active_link_to "Facilities", facilities_path, :wrap_tag => :li if current_user.try(:admin?) %>
        </li>
        <li>
            <%= active_link_to "Areas", areas_path, :wrap_tag => :li if current_user.try(:admin?) %>
        </li>
        <li>
            <%= active_link_to "Programs", programs_path, :wrap_tag => :li if current_user.try(:admin?) %>
        </li>
        <li>
            <%= active_link_to "Bus List", buses_path, :wrap_tag => :li if current_user.try(:admin?) %>
        </li>
<!--         <li>
            <%= active_link_to "Incident Types", incident_types_path, :wrap_tag => :li if current_user.try(:admin?) %>
        </li> -->
        <li>
            <%= active_link_to "Severity Levels", severity_levels_path, :wrap_tag => :li if current_user.try(:admin?) %>
        </li>
    <% end %>
  </ul>
</div>

app/views/shared/_sign_up_modal.html.erb
<div class="modal hide fade in" id="sign_up">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h2>Sign Up</h2>
	</div>
	<div class="modal-body">
		<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
		<%= devise_error_messages! %>
		<div>
		<%= f.label :email %>
		<br />
		<%= f.email_field :email, :autofocus => true %>
		</div>
		<div>
		<%= f.label :password %>
		<br />
		<%= f.password_field :password %>
		</div>
		<div>
		<%= f.label :password_confirmation %>
		<br />
		<%= f.password_field :password_confirmation %>
		</div>
	</div>
	<div class="modal-footer">
		<p>
			<div>
				<%= f.submit "Sign up", :class => 'btn btn-small btn-success' %>
			</div>
		</p>
		<p>
			<a href="#" class="btn btn-small" data-dismiss="modal">Close</a>
		</p>
	</div>
	<% end %>
</div>